config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "users#index"



  # IMP : if we write resource we only get one route but if we write resources we get seven routes ,  you can check that using "rails routes "

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy], controller: 'comments'
      resources :likes, only: [:create, :destroy], controller: 'likes'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :users do
        resources :posts do
          collection do
            get 'all'
          end
          resources :comments, only: [:index, :create]
        end
      end
    end
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  alias_attribute :author, :user

  after_create :increment_comments
  before_destroy :decrement_comments

  # after_create :update_comments_counter
  validates :author, presence: true
  validates :text, presence: true

  # def update_comments_counter
  #   post.update(comments_counter: post.comments.count)
  # end

  private

  def increment_comments
    post.increment!(:comments_counter)
  end

  def decrement_comments
    post.decrement!(:comments_counter)
  end
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < ApplicationController
  def index
    set_user
    set_post
    set_comments

    comments_data = @comments.map do |comment|
      {
        id: comment.id,
        text: comment.text,
        author_name: comment.user.name
      }
    end

    pretty_json = JSON.pretty_generate(comments_data)
    render json: pretty_json, status: :ok
  end

  def create
    set_user
    set_post

    @comment = @post.comments.build(comment_params.merge(user: current_user))

    if @comment.save
      render json: @comment.as_json(include: :user), status: :created
    else
      render json: { error: @comment.errors.full_messages }, status: :unprocessable_entity

    end
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_post
    set_user
    @post = @user.posts.find(params[:post_id])
  end

  def set_comments
    set_post
    @comments = @post.comments.includes(:user)
  end

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # load_and_authorize_resource

  def new
    Post.includes(:comments).find(params[:post_id])
    @comment = Comment.new
  end

  def create
    post = Post.find(params[:post_id])
    @comment = Comment.create(post_params(post))
    if @comment.save
      flash[:notice] = 'Comment created successfully'
      redirect_to user_post_path(current_user, post)
    else
      flash.now[:error] = "Error: Couldn't create comment"
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @post = @comment.post

    if current_user_can_delete_comment?(@comment)
      @comment.destroy
      flash[:notice] = 'Comment successfully deleted.'
    else
      flash[:alert] = 'You are not authorized to delete this comment.'
    end

    redirect_to user_post_path(@post.author, @post)
  end

  private

  def post_params(post)
    a_post = params.require(:comment).permit(:text)
    a_post[:author] = current_user
    a_post[:post] = post
    a_post
  end

  def current_user_can_delete_comment?(comment)
    current_user == comment.user || current_user.role == 'admin'
  end
end

app/views/comments/_comment.html.erb
<p><%= comment.user.name %> => <%= comment.text %></p>

<% if can?(:destroy, Comment) %>
  <%= button_to 'Delete This Comment', user_post_comment_path(user_id: comment.user_id, post_id: comment.post_id, id: comment.id), method: :delete, data: { confirm: 'Are you sure you want to delete this comment?' } %>
<% end %>

app/views/comments/_comment_form.html.erb
<h3>Add New Comment</h3>

<%= form_with(model: comment, url: user_post_comments_path(post.author, post)) do |f| %>
  <div>
    <%= f.label :Comment %>
    <br />
    <%= f.text_area :text, placeholder: "Type your comment here" %>
  </div>

  <%= f.submit 'Add New Comment' %>
<% end %>

app/views/comments/new.html.erb
<%= render partial: 'comments/comment_form', locals: { comment: Comment.new, post: @post, submit_label: 'Add Comment' } %>

app/views/comments/show.html.erb
<!-- all the comments to be displyed in this filr this collection will render all the comments innthe databse -->

<h1><%= @post.title %></h1>
<%= render partial: 'posts/post', locals: { post: @post } %>
<%= render partial: 'comments/comment_form', locals: { post: @post, comment: @comment } %>
<%= render partial: 'comments/comment', collection: @post.comments %>