config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "users#index"



  # IMP : if we write resource we only get one route but if we write resources we get seven routes ,  you can check that using "rails routes "

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy], controller: 'comments'
      resources :likes, only: [:create, :destroy], controller: 'likes'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :users do
        resources :posts do
          collection do
            get 'all'
          end
          resources :comments, only: [:index, :create]
        end
      end
    end
  end

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  after_create :increment_posts_number
  after_destroy :decrement_posts_number

  validates :title, presence: true, length: { maximum: 250 }
  validates :text, presence: true
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def increment_posts_number
    # belongs_to :author at top hence
    author.update(posts_counter: author.posts_counter + 1)
  end

  def decrement_posts_number
    author.update(posts_counter: author.posts_counter - 1)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  before_action :set_user
  before_action :set_post, only: [:show]

  def index
    @posts = @user.posts.includes(:comments, :likes)
    json_response = {
      posts: @posts.as_json(include: { comments: { include: :user }, likes: {} })
    }
    render json: JSON.pretty_generate(json_response)
  end

  def all
    @posts = Post.all

    json_response = {
      # %i used to exclude attributeasd
      posts: @posts.as_json(except: %i[comments likes])
    }

    render json: JSON.pretty_generate(json_response)
  end

  def show
    @comments = @post.comments.includes(:user)
    json_response = {
      post: @post.as_json(include: { comments: { include: :user } })
    }

    render json.pretty_generate(json_response)
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  rescue ActiveRecord::RecordNotFound
    render json: { error: 'No User Found' }, status: :not_found
  end

  def set_post
    @post = Post.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render json: { error: 'No Post Found' }, status: :not_found
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  before_action :set_user
  before_action :set_post, only: [:show]

  def index
    @posts = @user.posts.includes(:comments)
  end

  def show
    @comments = @post.comments
  end

  def new
    @post = Post.new
  end

  def create
    @post = @user.posts.build(post_params)

    if @post.save
      redirect_to user_posts_path(@user, @post), notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to user_posts_path(@user), notice: 'Post was successfully destroyed.'
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_post
    @post = @user.posts.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :text, :author_id)
  end
end

app/views/posts/_post.html.erb
<article style="display: flex; justify-content: space-between; border: 2px solid grey; padding: 4px;">

  <div>
    <%= link_to user_post_path(@user, post) do %>
    <h3>Post #<%= post.id %></h3>
    <% end %>

    <p><%= post.text %></p>
  </div>

  <div class="actions-container" style="display: flex; flex-direction:column; ">
    <p>
      <%= link_to "Comments: #{post.comments_counter}", user_post_path(post.author, post) %>
    </p>
    <p class="no-of-likes" style="margin-top: -5px;">Likes: <%= post.likes_counter %></p>
    <%= render partial: 'likes/like_form', locals: { post: post } %>
  </div>

</article>

app/views/posts/_post_with_comments.html.erb
<section style="margin-top: 4px;">
  <%= render partial: 'posts/post', locals: { post: post } %>
  
  <div style="border: 1px solid grey; padding:4px;">
      <% if can? :destroy, @post %>
      <%= button_to "Delet This Post" ,[@post.author, @post], method: :delete %>
      <% end %>
    <% if post.comments.present? %>
      <% post.recent_comments.each do |comment| %>
        <%= render partial: 'comments/comment', locals: { comment: comment } %>
      <% end %>
    <% else %>
      <p>No comment . click on post to add new comment</p>
    <% end %>
  </div>
</section>

app/views/posts/index.html.erb
<%= render partial: 'users/user', locals: { user: @user } %>

<% @posts.each do |post| %>
  <%= render partial: 'posts/post_with_comments', locals: { post: post } %>
<% end %>

<p style="display: flex; justify-content: center; text-shadow: 2px 2px 4px grey;">
  <span style="border: 3px solid grey; padding: 4px"> <%= link_to 'New Post', new_user_post_path(@user) %></span>
  <% if can? :read, @post %>
  <% link_to "View", @post%>
  <% end %>
</p>

app/views/posts/new.html.erb
<h3>Create a post</h3>
<%= form_with(model: Post.new, url: user_posts_path(@user), method: :post) do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :text %>
    <%= form.text_area :text %>
  </div>

  <%= form.hidden_field :author_id, value: current_user.id %>

  <div>
    <%= form.submit 'submit' %>
  </div>
<% end %>

app/views/posts/show.html.erb
<div class="random" style="display: flex; justify-content: space-between; border: 2px solid grey;">
  <div>
    <h3>Post #<%= @post.id %> by <%= @post.author.name %></h3>
    <div>
      <p><%= @post.text %></p>
    </div>
    <%= render partial: 'likes/like_form', locals: { post: @post } %>

  </div>
  <div style="display: flex; padding: 6px; gap: 10px">
    <% if can? :destroy, @post %>
    <%= button_to "Delet This Post" ,[@post.author, @post], method: :delete %>
    <% end %>

    <p>Comments: <%= @post.comments_counter %></p>
    <p>Likes: <%= @post.likes_counter %></p>
  </div>
</div>

<article style="border: 1px solid gray">
  <%= render partial: 'comments/comment_form', locals: { post: @post, comment: Comment.new } %>

  <% if @comments&.any? %>
    <%= render partial: 'comments/comment', collection: @comments %>
  <% else %>
    <p>No comments yet.</p>
  <% end %>
</article>